---
logging:
 level:
    com.sap.cds.security.authentication: DEBUG
spring:
  web.resources.static-locations: "file:./app/webapp"
  config.activate.on-profile: default
  datasource:
    url: "jdbc:sqlite:/home/user/projects/WellCompletion/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never # original value always ...if you keep always on starting your entries would be deleted
    hikari:
      maximum-pool-size: 1

cds:
 security.mock.users:
  - name: MasterDataAdmin
    password: admin
    roles:
    - MasterDataAdmin  


  - name: user
    password: user
    roles: 
    - Viewer
    - MediumAdmin
    - MasterDataAdmin
    attributes:
     countryassigned: [DE, UK]
    additional: 
     email: rajesh.kumar.khatwa@sap.com

  - name: superAdmin
    password : admin
    privileged: true  # it bypasses all the authorization checks