---
spring:
  web.resources.static-locations: "file:./app/webapp"
  config.activate.on-profile: cloud


#To clear Cache for username : restart the chrome browser  chrome://restart

cds:
 security.mock.users:
  - name: MasterDataAdmin
    password: admin
    roles:
    - MasterDataAdmin  


  - name: user
    password: user
    roles: 
    - Viewer
    attributes:
     countryassigned: [DE, UK]
    additional: 
     email: rajesh.kumar.khatwa@sap.com

  - name: superAdmin
    password : admin
    privileged: true  # it bypasses all the authorization checks